### ISSUE TITLE
enhancement/bug: support for sub paths

### ISSUE THREAD

**Issue by dbehnke** [kc1awv/gomrefdash#13]
One thing forgot to consider while developing was to test and support for sub paths.. i.e.   https://somehostname/m17dash/ 

This may be a trivial change of simply removing the forward / at beginning.   Or we may need to add a sub path parameter to our config and find a way to propagate that to the JavaScript.    One idea if we have to propagate to the JavaScript is possibly move the JavaScript in with the templated file instead of separate files and add a prefix.   Will need to sit down with this and possibly get inspiration from other projects out there doing similar things.

**Comment by kc1awv** [comment]
> add a sub path parameter to our config

I think that's the best idea.

**Comment by dbehnke** [comment]
think this can be closed .. fixed in #14 -- reopen it if anything else needs to be added
