### ISSUE TITLE
Autorefresh page based on mrefd log file changes instead of a meta refresh

### ISSUE THREAD

**Issue by kc1awv** [kc1awv/gomrefdash#2]
Meta refresh creates too much noise and refreshes regardless of changing data. Is there a way to tell the browser to refresh the page only when data changes in the log file?

**Comment by dbehnke** [comment]
I have some ideas I'll take a stab at this.. since this is a full fledged go app we can do some caching tricks server side and check the file.. and maybe some javascript tricks browser side that poll.
