### ISSUE TITLE
dark mode switch

### ISSUE THREAD

**Issue by kc1awv** [kc1awv/gomrefdash#21]
Simple as that. Switch the CSS from light to dark, with the initial color scheme selected based on the browser / OS theme.

**Comment by NNL-Keerthana** [comment]
I would like to work on this issue

**Comment by dbehnke** [comment]
i have this option now available in the quasar branch i been working on but can leave this open until it get merged in.

**Comment by dbehnke** [comment]
going to close this since we have solution merged in now.
