### ISSUE TITLE
Service Uptime?

### ISSUE THREAD

**Issue by n7tae** [kc1awv/gomrefdash#25]
The old dashboard had a Service Uptime in the top menu bar. I believe it used the mrefd.pid file to calc this. Can you bring it back, at least as a configurable option?

**Comment by kc1awv** [comment]
Dropping this here as a reference. Possibly could be handled with this package.

https://godocs.io/github.com/shirou/gopsutil/v3/process

**Comment by dbehnke** [comment]
yeah we can look at the pid file if its still there.. I'm kinda close on my quasar ui branch being able to merge it in and i'll add that to the list of things todo.  The gopsutil could be useful, might need to check how cross platform it is.. not that i think people will run stuff on windows.. but you never know.

**Comment by dbehnke** [comment]
was looking into this today.  this won't be possible to check process is running if folks have the dashboard running in a docker container as it can't see or query os processes other than inside the container.  The best we could possibly do in this case is check the date on the pid file for age, and date on the mrefd.xml file.. as long as its getting refreshed service is up.

**Comment by dbehnke** [comment]
i can code the traditional way of checking os process.. and fallback to pid file date / check mrefd.xml if os process query fails.

**Comment by dbehnke** [comment]
ChatGPT helped me with some code btw ;) will be modifying this for our use case.

To check if a process is alive and get its uptime in Go, you can use the syscall package to read the PID from the file and then use the FindProcess function from the os package to check if the process is still running. Here's an example of how you could do this:

```
package main

import (
	"bufio"
	"fmt"
	"os"
	"syscall"
	"time"
)

func processAlive(pid int) bool {
	// Check if the process is alive
	process, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	err = process.Signal(syscall.Signal(0))
	if err == nil {
		return true
	}
	return false
}

func processUptime(pid int, startTime time.Time) time.Duration {
	// Check the process uptime
	uptime := time.Since(startTime)
	return uptime
}

func main() {
	// Read the PID from the file
	pidFile, err := os.Open("/path/to/pid_file.txt")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	defer pidFile.Close()

	scanner := bufio.NewScanner(pidFile)
	if scanner.Scan() {
		pid, err := strconv.Atoi(scanner.Text())
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}

		if processAlive(pid) {
			// Read the start time from the file
			startTime, err := readStartTimeFromFile("/path/to/start_time_file.txt")
			if err != nil {
				fmt.Println(err)
				os.Exit(1)
			}

			uptime := processUptime(pid, startTime)
			fmt.Printf("Process is alive and has been running for %s\n", uptime)
		} else {
			fmt.Println("Process is not alive")
		}
	} else {
		fmt.Println("Error reading PID from file")
		os.Exit(1)
	}
}
```

**Comment by dbehnke** [comment]
Proposed Solution:

```
package main

import (
	"fmt"
	"os"
	"time"
)

func timeSinceModified(filename string) (time.Duration, error) {
	file, err := os.Open(filename)
	if err != nil {
		return 0, err
	}
	defer file.Close()

	fileInfo, err := file.Stat()
	if err != nil {
		return 0, err
	}

	modifiedTime := fileInfo.ModTime()
	timeSinceModified := time.Since(modifiedTime)
	return timeSinceModified, nil
}

func isModifiedOver2MinutesAgo(filename string) (bool, error) {
	file, err := os.Open(filename)
	if err != nil {
		return false, err
	}
	defer file.Close()

	fileInfo, err := file.Stat()
	if err != nil {
		return false, err
	}

	modifiedTime := fileInfo.ModTime()
	timeSinceModified := time.Since(modifiedTime)
	if timeSinceModified > (2 * time.Minute) {
		return true, nil
	}
	return false, nil
}

func mrefdUptime(pidFile, checkFile string) (time.Duration, error) {
	uptime, err := timeSinceModified(pidFile)
	if err != nil {
		return 0, err
	}
	stale, err := isModifiedOver2MinutesAgo(checkFile)
	if err != nil {
		return 0, err
	}
	if stale {
		return uptime, fmt.Errorf("check file is older than two minutes")
	}
	return uptime, nil
}

func main() {
	pidFile := "/var/run/mrefd.pid"
	checkFile := "/var/log/mrefd.xml"
	uptime, err := mrefdUptime(pidFile, checkFile)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	fmt.Printf("mrefd has been up for %s", uptime)
}
```

With the following files..
```
❯ ls -lh /var/run/mrefd.pid /var/log/mrefd.xml
-rw-r--r-- 1 root root 7.9K Jan  2 16:56 /var/log/mrefd.xml
-rw-r--r-- 1 root root    8 Dec 20 21:56 /var/run/mrefd.pid
```

Sample Output:

```
❯ go run check.go
mrefd has been up for 307h0m11.06487047s
```

**Comment by dbehnke** [comment]
https://m17.ac8zd.com has a demo.. bottom of the page..

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/916775/210286308-19576eae-40b9-48e5-aa5c-769af253850c.png">

code available here.. https://github.com/dbehnke/gomrefdash/tree/dbehnke/quasar

**Comment by n7tae** [comment]
Looks good, a clean design! A few minor comments:

- Looks like the `Callsign` column heading on the home page is using center justified while the callsigns are right justified. It might look nicer if they were centered as well. Personally, I would prefer left justified with a fixed width font.
- In the footer, the two instances of `mrefd` are not needed.
- `NONE` is not needed if there is no IPv6 connectivity.
- Resizing my browser window works really well, even for extreme rectangles! It even works well on my iPhone.
- The blue color for the Sysop link is hard to see.

And this one is especially minor: How about if the three tabs were center justified, leaving the dark/light mode on the right side?

**Comment by kc1awv** [comment]
Can we migrate your quasar branch to this repo?

**Comment by dbehnke** [comment]
yeah let me implement n7tae's suggestions first.. one issue we will have though is that sub paths won't work if we merge it.. the frontend has to be compiled with nodejs stuff to do sub paths correctly which can be a pain for some folks.

**Comment by dbehnke** [comment]
going to close this since we merged in quasar.
