### ISSUE TITLE
Add country flags to callsigns on last heard page

### ISSUE THREAD

**Issue by kc1awv** [kc1awv/gomrefdash#3]
Simple as that, add in the country flags for callsigns on the last heard page. This is a feature in the old PHP implementation that would like to be carried over to the new one.
![Screenshot 2022-10-01 152519](https://user-images.githubusercontent.com/43918257/193425147-30481c4e-55a2-4f50-a733-86c22725d838.png)

**Comment by samyaksand** [comment]
Hello, Im interested in working on this. Please assign me this issue.

**Comment by kc1awv** [comment]
If you need an example mrefd log file, here you go! Just rename to mrefd.xml, and put it in the same folder as main.go. Line 39 in models.reflector.go points to that file, just uncomment it and comment line 40.
[mrefd.txt](https://github.com/kc1awv/gomrefdash/files/9691056/mrefd.txt)

**Comment by dbehnke** [comment]
fun with flags merged into main
