### ISSUE TITLE
I installed gomrefdash, but it doesn't work. (solved)

### ISSUE THREAD

**Issue by ds5qdr** [kc1awv/gomrefdash#34]
I installed the M17-QDR and it works fine when I access it on Androidstar.

But I installed gomrefdash, but it doesn't work.
Please let me know if there is a step by step setting method.
And my gomrefdash.sample.toml file and mrefd.xml file are as follows.

pi@m17:~/gomrefdash $ cat gomrefdash.sample.toml
hostport=":3000" # e.g. 127.0.0.1:3000 for only localhost
ipv4="127.0.0.1"
ipv6="01:02:03:04:05:06"
refresh=10
lastheard=20
mreffile="/var/log/mrefd.xml"
mrefpidfile="/var/run/mrefd.pid"
email="sysop@m17reflector.xyz"
debug=false # debug mode on, logs more information
subpath="" # e.g. "/reflector" would be http://yourhostname/reflector, leave blank for no sub path
callsigncountryfile="callsign_country.csv"

pi@m17:~/gomrefdash $ cat /var/log/mrefd.xml
<?xml version="1.0" encoding="UTF-8"?>
<REFLECTOR CALLSIGN="M17-QDR">
<VERSION>0.11.3-dht</VERSION>
<PEERS>
</PEERS>
<NODES>
</NODES>
<STATIONS>
<STATION>
        <CALLSIGN>6K5AMR  D</CALLSIGN>
        <VIANODE>6K5AMR  D</VIANODE>
        <ONMODULE>C</ONMODULE>
        <VIAPEER>M17-QDR</VIAPEER>
        <LASTHEARDTIME>2023-10-14T13:32:20Z</LASTHEARDTIME>
</STATION>
</STATIONS>
</REFLECTOR>
pi@m17:~/gomrefdash $

./gomrefdash is as follows
pi@m17:~/gomrefdash $ ./gomrefdash
2023/10/15 09:01:56 Starting ./gomrefdash 0.4.4-dc0d042
2023/10/15 09:01:56 gomrefdash.toml found.
2023/10/15 09:01:56 loading country callsigns from file

**Comment by kc1awv** [comment]
You're running the sample file, and not one edited for your system? Even so, the program should run regardless, just with bogus information for your IP addresses and email.

The mrefd log file doesn't look properly formatted. It should be in XML format, not a single line as shown in your example.

**Comment by ds5qdr** [comment]
Thank you for your quick reply.

My mrefd log file is as follows.
pi@m17:~ $ sudo journalctl -u mrefd -f
Oct 14 22:57:05 m17 mrefd[13666]: PutDHTClients() successful
Oct 14 23:24:34 m17 mrefd[13666]: Disconnect packet from 6K5AMR  D at 192.168.0.1:60761
Oct 14 23:24:34 m17 mrefd[13666]: Client 6K5AMR  D at 192.168.0.1:60761 removed with protocol M17 on module C
Oct 14 23:24:36 m17 mrefd[13666]: PutDHTClients() successful
Oct 15 13:25:19 m17 mrefd[13666]: Connect packet for module C from 6K5AMR  D at 192.168.0.1:46018
Oct 15 13:25:19 m17 mrefd[13666]: New client 6K5AMR  D at 192.168.0.1:46018 added with protocol M17 on module C
Oct 15 13:25:22 m17 mrefd[13666]: PutDHTClients() successful
Oct 15 13:25:22 m17 mrefd[13666]: Connect packet for module C from DS5QDR  D at 192.168.0.1:42022
Oct 15 13:25:22 m17 mrefd[13666]: New client DS5QDR  D at 192.168.0.1:42022 added with protocol M17 on module C
Oct 15 13:25:24 m17 mrefd[13666]: PutDHTClients() successful
Oct 15 13:28:36 m17 mrefd[13666]: Opening stream on module C for client DS5QDR  D with id 0x4c71 by user DS5QDR  D
Oct 15 13:28:38 m17 mrefd[13666]: PutDHTUsers() successful
Oct 15 13:28:42 m17 mrefd[13666]: Closing stream on module C
Oct 15 13:28:52 m17 mrefd[13666]: Opening stream on module C for client 6K5AMR  D with id 0x9818 by user 6K5AMR  D
Oct 15 13:28:54 m17 mrefd[13666]: PutDHTUsers() successful
Oct 15 13:28:59 m17 mrefd[13666]: Closing stream on module C
Oct 15 13:29:53 m17 mrefd[13666]: Disconnect packet from DS5QDR  D at 192.168.0.1:42022
Oct 15 13:29:53 m17 mrefd[13666]: Client DS5QDR  D at 192.168.0.1:42022 removed with protocol M17 on module C
Oct 15 13:29:55 m17 mrefd[13666]: PutDHTClients() successful

My xml file is as follows
pi@m17:~ $ cat /var/log/mrefd.xml
<?xml version="1.0" encoding="UTF-8"?>
<REFLECTOR CALLSIGN="M17-QDR">
<VERSION>0.11.3-dht</VERSION>
<PEERS>
</PEERS>
<NODES>
<NODE>
        <CALLSIGN>6K5AMR  D</CALLSIGN>
        <IP>192.168.0.1</IP>
        <LINKEDMODULE>C</LINKEDMODULE>
        <PROTOCOL>M17</PROTOCOL>
        <CONNECTTIME>2023-10-15T04:25:19Z</CONNECTTIME>
        <LASTHEARDTIME>2023-10-15T04:28:52Z</LASTHEARDTIME>
</NODE>
</NODES>
<STATIONS>
<STATION>
        <CALLSIGN>6K5AMR  D</CALLSIGN>
        <VIANODE>6K5AMR  D</VIANODE>
        <ONMODULE>C</ONMODULE>
        <VIAPEER>M17-QDR</VIAPEER>
        <LASTHEARDTIME>2023-10-15T04:28:52Z</LASTHEARDTIME>
</STATION>
<STATION>
        <CALLSIGN>DS5QDR  D</CALLSIGN>
        <VIANODE>DS5QDR  D</VIANODE>
        <ONMODULE>C</ONMODULE>
        <VIAPEER>M17-QDR</VIAPEER>
        <LASTHEARDTIME>2023-10-15T04:28:36Z</LASTHEARDTIME>
</STATION>
</STATIONS>
</REFLECTOR>


M17-QDR dashboard 
url은 m17-qdr.duckdns.org
ip is 119.199.235.196
It is.

The go language was installed according to the site guide below
https://go.dev/doc/install

pi@m17:~ $ export PATH=$PATH:/usr/local/go/bin
pi@m17:~ $ go version
go version go1.21.3 linux/arm


After go compilation, the files in the directory are as follows
pi@m17:~/gomrefdash $ ls -l
total 10336
drwxr-xr-x 4 pi pi     4096 Oct 14 23:11 backend
-rw-r--r-- 1 pi pi     9192 Oct 14 23:11 callsign_country.csv
-rw-r--r-- 1 pi pi     1103 Oct 14 23:11 docker-compose.sample.yml
-rw-r--r-- 1 pi pi      397 Oct 14 23:11 Dockerfile
-rwxr-xr-x 1 pi pi      159 Oct 14 23:11 entrypoint.sh
drwxr-xr-x 4 pi pi     4096 Oct 14 23:11 frontend
-rw-r--r-- 1 pi pi     1026 Oct 14 23:11 go.mod
-rwxr-xr-x 1 pi pi 10232209 Oct 14 23:12 gomrefdash
-rw-r--r-- 1 pi pi      411 Oct 14 23:11 gomrefdash.sample.toml
-rw-r--r-- 1 pi pi      405 Oct 14 23:22 gomrefdash.toml
-rw-r--r-- 1 pi pi    11375 Oct 14 23:11 go.sum
-rw-r--r-- 1 pi pi    35148 Oct 14 23:11 LICENSE
-rw-r--r-- 1 pi pi   187150 Oct 14 23:11 m17dashboard-screenshot.png
-rw-r--r-- 1 pi pi    38076 Oct 14 23:11 m17reflectors.png
-rw-r--r-- 1 pi pi     1340 Oct 14 23:11 Makefile
-rw-r--r-- 1 pi pi     9348 Oct 14 23:11 README.md
-rw-r--r-- 1 pi pi        6 Oct 14 23:11 VERSION

Thank you.

**Comment by kc1awv** [comment]
I still see nothing that would cause an issue. No explanation of expected result vs actual result.

**Comment by ds5qdr** [comment]
Good News!

I solved my issue.
rebuild gomrefdash and modify gomrefdash.toml!
Thanks your helps

DS5QDR Heonmin Lee.

![image](https://github.com/kc1awv/gomrefdash/assets/64110724/a2f94102-31d5-4e7b-abac-122c4f15dff5)
