### ISSUE TITLE
Error compiling-> gcc: error: unrecognized command-line option '-m64'

### ISSUE THREAD

**Issue by MuevCFO** [kc1awv/gomrefdash#37]
```
root@Allstar:/home/wbs/temp# go version
go version go1.23.4 linux/amd64
root@Allstar:/home/wbs/temp# cd gomrefdash/
root@Allstar:/home/wbs/temp/gomrefdash# make
cd backend/cmd/dashboard && GOOS= GOARCH= GOARM= go build -o ../../../gomrefdash -ldflags "-X main.dver=0.5.0-d3c5126"
go: downloading github.com/gin-gonic/gin v1.9.1
go: downloading github.com/BurntSushi/toml v1.3.2
go: downloading github.com/gin-contrib/sse v0.1.0
go: downloading github.com/mattn/go-isatty v0.0.19
go: downloading golang.org/x/net v0.17.0
go: downloading github.com/pelletier/go-toml/v2 v2.1.0
go: downloading github.com/go-playground/validator/v10 v10.15.5
go: downloading github.com/ugorji/go/codec v1.2.11
go: downloading google.golang.org/protobuf v1.31.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading golang.org/x/sys v0.13.0
go: downloading github.com/gabriel-vasile/mimetype v1.4.3
go: downloading github.com/go-playground/universal-translator v0.18.1
go: downloading github.com/leodido/go-urn v1.2.4
go: downloading golang.org/x/crypto v0.14.0
go: downloading golang.org/x/text v0.13.0
go: downloading github.com/go-playground/locales v0.14.1
# runtime/cgo
gcc: error: unrecognized command-line option '-m64'
make: *** [Makefile:14: gomrefdash] Error 1
```

Server: Linux Allstar 6.6.62+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux

**Comment by kc1awv** [comment]
Looks like a distro specific issue. Builds fine on aarch64 here.

**Comment by MuevCFO** [comment]
Any clues on fixing the issue?  From the brief research it seems one of the products doesn't either have or know where the cross files are located...

**Comment by kc1awv** [comment]
Nope. Shouldn't be cross compiling to begin with, builds from source to generate a binary for the machine you intend to run it on. Either gcc is fucked, or you might need to set Go environment variables. ¯\_(ツ)_/¯ Simply posting the error and uname doesn't help diagnose the issue other than have me test build locally on the same arch if it's available.

**Comment by MuevCFO** [comment]
So doubled checked $PATH, and was able to execute go version.

Probably missing a library for cross -m64.  whatever m64 is....

**Comment by MuevCFO** [comment]
FYI:
root@Allstar:/home/wbs/temp/gomrefdash# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/12/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 12.2.0-14' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Debian 12.2.0-14) 
root@Allstar:/home/wbs/temp/gomrefdash#

**Comment by MuevCFO** [comment]
I think the error may be this line:

cd backend/cmd/dashboard && GOOS=$(GOOS) GOARCH=$(GOARCH) GOARM=$(GOARM) go build -o ../../../gomrefdash -ldflags "-X main.dver=$(VERSION)"
